<?php

// Generated by `wp configmaps update` on 2022-01-13T12:10:41+00:00.

return [
  'metadata' => [
    'version' => 1,
  ],
  'data' => [
    'WPLANG' => 'sl_SI',
    'active_plugins' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        0 => 'imsanity/imsanity.php',
        1 => 'pdkranj-robotstxt/pdkranj-robotstxt.php',
        2 => 'post-expirator/post-expirator.php',
        3 => 'simple-page-to-sidebar/simple-page-to-sidebar.php',
      ],
    ],
    'admin_email' => 'janez.nastran@pdkranj.si',
    'admin_email_lifespan' => '2000000000',
    'auto_core_update_notified' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        'email' => 'bojan.hribernik@gmail.com',
        'timestamp' => 1484684776,
        'type' => 'manual',
        'version' => '4.7.1',
      ],
    ],
    'auto_plugin_theme_update_emails' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
      ],
    ],
    'auto_update_core_dev' => 'enabled',
    'auto_update_core_major' => 'unset',
    'auto_update_core_minor' => 'enabled',
    'avatar_default' => 'mystery',
    'avatar_rating' => 'G',
    'blog_charset' => 'UTF-8',
    'blog_public' => '1',
    'blogdescription' => 'Planinsko društvo Kranj',
    'blogname' => 'PD Kranj',
    'can_compress_scripts' => [
      'action' => 'ignore',
      'type' => 'string',
    ],
    'category_base' => '',
    'category_children' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
      ],
    ],
    'close_comments_days_old' => '14',
    'close_comments_for_old_posts' => '',
    'comment_max_links' => '2',
    'comment_moderation' => '',
    'comment_order' => 'asc',
    'comment_previously_approved' => '1',
    'comment_registration' => '1',
    'comments_notify' => '1',
    'comments_per_page' => '50',
    'current_theme' => 'PD Kranj Bootstrap 5',
    'dashboard_widget_options' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        'dashboard_incoming_links' => [
          'type' => 'array',
          'value' => [
            'home' => 'https://UNDEFINED-IN-CONFIGMAPS.dev.pdkranj.si',
            'items' => 10,
            'link' => 'http://blogsearch.google.com/blogsearch?scoring=d&partner=wordpress&q=link:https://UNDEFINED-IN-CONFIGMAPS.dev.pdkranj.si/',
            'show_date' => false,
            'url' => 'http://blogsearch.google.com/blogsearch_feeds?scoring=d&ie=utf-8&num=10&output=rss&partner=wordpress&q=link:http://pdkranj.lan/',
          ],
        ],
        'dashboard_primary' => [
          'type' => 'array',
          'value' => [
            'items' => 2,
            'link' => 'http://wordpress.org/news/',
            'show_author' => 0,
            'show_date' => 1,
            'show_summary' => 1,
            'title' => 'WordPress Blog',
            'url' => 'http://wordpress.org/news/feed/',
          ],
        ],
        'dashboard_recent_comments' => [
          'type' => 'array',
          'value' => [
            'items' => 5,
          ],
        ],
        'dashboard_secondary' => [
          'type' => 'array',
          'value' => [
            'items' => 5,
            'link' => 'http://sl.wordpress.org/',
            'show_author' => 0,
            'show_date' => 0,
            'show_summary' => 0,
            'title' => 'Novice iz WordPress Slovenija',
            'url' => 'http://sl.wordpress.org/feed/',
          ],
        ],
      ],
    ],
    'date_format' => 'j.n.Y',
    'db_upgraded' => [
      'action' => 'ignore',
      'type' => 'string',
    ],
    'db_version' => [
      'action' => 'ignore',
      'type' => 'string',
    ],
    'default_category' => '2',
    'default_comment_status' => 'closed',
    'default_comments_page' => 'newest',
    'default_email_category' => '1',
    'default_link_category' => '0',
    'default_ping_status' => 'closed',
    'default_pingback_flag' => '',
    'default_post_format' => '0',
    'default_role' => 'subscriber',
    'disallowed_keys' => '',
    'facebook_migration_10' => '1',
    'facebook_migration_115' => '1',
    'facebook_migration_118' => '1',
    'finished_splitting_shared_terms' => '1',
    'finished_updating_comment_type' => [
      'action' => 'ignore',
      'type' => 'string',
    ],
    'fpw_options' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        'version' => '1.2.2',
      ],
    ],
    'ftp_credentials' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        'connection_type' => 'ftps',
        'hostname' => 'bivak.s.itsis.si',
        'username' => 'pd_bojan',
      ],
    ],
    'gmt_offset' => '',
    'hack_file' => '0',
    'home' => 'https://UNDEFINED-IN-CONFIGMAPS.dev.pdkranj.si',
    'html_type' => 'text/html',
    'image_default_align' => '',
    'image_default_link_type' => 'file',
    'image_default_size' => '',
    'imsanity_bmp_to_jpg' => '1',
    'imsanity_delete_originals' => '',
    'imsanity_max_height' => '1280',
    'imsanity_max_height_library' => '1280',
    'imsanity_max_height_other' => '1280',
    'imsanity_max_width' => '1280',
    'imsanity_max_width_library' => '1280',
    'imsanity_max_width_other' => '1280',
    'imsanity_png_to_jpg' => '',
    'imsanity_quality' => '90',
    'imsanity_version' => '2.7.2',
    'initial_db_version' => '22442',
    'large_size_h' => '1024',
    'large_size_w' => '1024',
    'link_manager_enabled' => '0',
    'links_updated_date_format' => 'j. F, Y G:i',
    'mailserver_login' => 'login@example.com',
    'mailserver_pass' => 'password',
    'mailserver_port' => '110',
    'mailserver_url' => 'mail.example.com',
    'mec_dyncss' => '',
    'mec_get_webnus_news_html' => 'O:8:"stdClass":5:{s:1:"1";O:8:"stdClass":3:{s:7:"content";s:126:"WordPress plugins are the soul of every WordPress website. They come in handy when you need to add extra functionality&hellip;";s:5:"title";s:67:"8 WordPress Plugins No Freelancer or Consultant Should Live Without";s:4:"link";s:71:"https://webnus.net/wordpress-plugins-no-freelancer-should-live-without/";}s:1:"2";O:8:"stdClass":3:{s:7:"content";s:118:"WordPress has taken the world by storm with over 64 million websites hosted on the platform. What started as a&hellip;";s:5:"title";s:33:"How to Sell on WordPress in 2021?";s:4:"link";s:44:"https://webnus.net/how-to-sell-on-wordpress/";}s:1:"3";O:8:"stdClass":3:{s:7:"content";s:135:"Creating a website is a requirement for the success of online businesses. WordPress has become popular among business owners as&hellip;";s:5:"title";s:81:"7 Best WordPress Practices for Students in Preparation for Writing a Dissertation";s:4:"link";s:80:"https://webnus.net/best-wordpress-practices-for-students-writing-a-dissertation/";}s:1:"4";O:8:"stdClass":3:{s:7:"content";s:102:"It is believed that it is better to output charts and graphs not with the help of a plugin but&hellip;";s:5:"title";s:62:"7 Best WordPress Plugins for Data Visualization and BI Reports";s:4:"link";s:80:"https://webnus.net/best-wordpress-plugins-for-data-visualization-and-bi-reports/";}s:1:"5";O:8:"stdClass":3:{s:7:"content";s:113:"The power of social media has taken the entire world by storm. Gone are the days where social media would&hellip;";s:5:"title";s:61:"How To Spot The Best Social Media Consulting Services in 2021";s:4:"link";s:66:"https://webnus.net/spot-the-best-social-media-consulting-services/";}}',
    'mec_get_webnus_news_time' => '2021-06-07',
    'mec_gfont' => '',
    'mec_installed' => '1',
    'mec_options' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        'gateways' => [
          'type' => 'array',
          'value' => [
            1 => [
              'type' => 'array',
              'value' => [
                'status' => 1,
              ],
            ],
          ],
        ],
        'notifications' => [
          'type' => 'array',
          'value' => [
            'admin_notification' => [
              'type' => 'array',
              'value' => [
                'content' => 'Dear Admin,

                    A new booking is received. Please check and confirm it as soon as possible.

                    %%admin_link%%
                    
                    %%attendees_full_info%%

                    Regards,
                    %%blog_name%%',
                'recipients' => '',
                'subject' => 'A new booking is received.',
              ],
            ],
            'booking_confirmation' => [
              'type' => 'array',
              'value' => [
                'content' => 'Hi %%name%%,

                    Your booking is confirmed. You should be available at %%book_date%% in %%event_location_address%%.

                    You can contact to event organizer by calling %%event_organizer_tel%%.

                    Regards,
                    %%blog_name%%',
                'recipients' => '',
                'subject' => 'Your booking is confirmed.',
              ],
            ],
            'booking_notification' => [
              'type' => 'array',
              'value' => [
                'content' => 'Hello %%name%%,

                    Your booking is received. We will check and confirm your booking as soon as possible.
                    Thanks for your patience.

                    Regards,
                    %%blog_name%%',
                'recipients' => '',
                'subject' => 'Your booking is received.',
              ],
            ],
            'booking_rejection' => [
              'type' => 'array',
              'value' => [
                'content' => 'Hi %%name%%,

                    For your information, your booking for %%event_title%% at %%book_date%% is rejected.
        
                    Regards,
                    %%blog_name%%',
                'recipients' => '',
                'send_to_admin' => '0',
                'send_to_organizer' => '1',
                'send_to_user' => '1',
                'status' => '0',
                'subject' => 'Your booking got rejected!',
              ],
            ],
            'cancellation_notification' => [
              'type' => 'array',
              'value' => [
                'content' => 'Hi %%name%%,

                    For your information, your booking for %%event_title%% at %%book_date%% is canceled.

                    Regards,
                    %%blog_name%%',
                'recipients' => '',
                'send_to_admin' => '1',
                'send_to_organizer' => '0',
                'send_to_user' => '0',
                'status' => '0',
                'subject' => 'Your booking is canceled.',
              ],
            ],
            'email_verification' => [
              'type' => 'array',
              'value' => [
                'content' => 'Hi %%name%%,

                    Please verify your booking by clicking on following link:

                    %%verification_link%%

                    Regards,
                    %%blog_name%%',
                'recipients' => '',
                'subject' => 'Please verify your booking.',
              ],
            ],
            'event_soldout' => [
              'type' => 'array',
              'value' => [
                'content' => 'Hi %%name%%,

                    For your information, your %%event_title%% event at %%book_date%% is soldout.
        
                    Regards,
                    %%blog_name%%',
                'recipients' => '',
                'send_to_admin' => '1',
                'send_to_organizer' => '1',
                'status' => '0',
                'subject' => 'Your event is soldout!',
              ],
            ],
            'new_event' => [
              'type' => 'array',
              'value' => [
                'content' => 'Hello,

                    A new event just added. The event title is %%event_title%% and its status is %%event_status%%.
                    The new event may need to be published. Please use this link for managing your website events: %%admin_link%%

                    Regards,
                    %%blog_name%%',
                'recipients' => '',
                'status' => '1',
                'subject' => 'A new event is added.',
              ],
            ],
            'user_event_publishing' => [
              'type' => 'array',
              'value' => [
                'content' => 'Hello %%name%%,

                    Your event gets published. You can check it below:

                    <a href="%%event_link%%">%%event_title%%</a>

                    Regards,
                    %%blog_name%%',
                'recipients' => '',
                'status' => '1',
                'subject' => 'Your event gets published',
              ],
            ],
          ],
        ],
        'settings' => [
          'type' => 'array',
          'value' => [
            'countdown_status' => 1,
            'default_skin_archive' => 'full_calendar',
            'export_module_status' => 1,
            'google_maps_status' => 1,
            'multiple_day_show_method' => 'first_day_listgrid',
            'sn' => [
              'type' => 'array',
              'value' => [
                'email' => 1,
                'facebook' => 1,
                'googlecal' => 1,
                'gplus' => 1,
                'ical' => 1,
                'linkedin' => 1,
                'twitter' => 1,
              ],
            ],
            'social_network_status' => 1,
          ],
        ],
        'styles' => [
          'type' => 'array',
          'value' => [
            'CSS' => '',
          ],
        ],
      ],
    ],
    'mec_version' => '5.19.5',
    'medium_large_size_h' => '0',
    'medium_large_size_w' => '768',
    'medium_size_h' => '300',
    'medium_size_w' => '300',
    'moderation_keys' => '',
    'moderation_notify' => '1',
    'nav_menu_options' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        0 => false,
        'auto_add' => [
          'type' => 'array',
          'value' => [
          ],
        ],
      ],
    ],
    'page_comments' => '',
    'page_for_posts' => '0',
    'page_on_front' => '0',
    'permalink_structure' => '/%year%/%monthnum%/%day%/%postname%/',
    'ping_sites' => 'http://rpc.pingomatic.com/',
    'posts_per_page' => '10',
    'posts_per_rss' => '10',
    'recently_activated' => [
      'action' => 'ignore',
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => NULL,
    ],
    'recently_edited' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        0 => '/var/home/pd/www/www.pdkranj.si/public/wp-content/themes/twentytwelve/header.php',
        2 => '/var/home/pd/www/www.pdkranj.si/public/wp-content/themes/twentytwelve/footer.php',
        3 => '/var/home/pd/www/www.pdkranj.si/public/wp-content/themes/twentytwelve/style.css',
        4 => '/var/home/pd/www/www.pdkranj.si/public/wp-content/themes/twentytwelve/tag.php',
        5 => '/var/home/pd/www/www.pdkranj.si/public/wp-content/themes/twentytwelve/single.php',
      ],
    ],
    'require_name_email' => '1',
    'rewrite_rules' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '(.?.+?)(?:/([0-9]+))?/?$' => 'index.php?pagename=$matches[1]&page=$matches[2]',
        '(.?.+?)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?pagename=$matches[1]&feed=$matches[2]',
        '(.?.+?)/comment-page-([0-9]{1,})/?$' => 'index.php?pagename=$matches[1]&cpage=$matches[2]',
        '(.?.+?)/embed/?$' => 'index.php?pagename=$matches[1]&embed=true',
        '(.?.+?)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?pagename=$matches[1]&feed=$matches[2]',
        '(.?.+?)/page/?([0-9]{1,})/?$' => 'index.php?pagename=$matches[1]&paged=$matches[2]',
        '(.?.+?)/trackback/?$' => 'index.php?pagename=$matches[1]&tb=1',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)(?:/([0-9]+))?/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&page=$matches[5]',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&feed=$matches[5]',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/comment-page-([0-9]{1,})/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&cpage=$matches[5]',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/embed/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&embed=true',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&feed=$matches[5]',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/page/?([0-9]{1,})/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&paged=$matches[5]',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/trackback/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&tb=1',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&feed=$matches[4]',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/comment-page-([0-9]{1,})/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&cpage=$matches[4]',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/embed/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&embed=true',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&feed=$matches[4]',
        '([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/page/?([0-9]{1,})/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&paged=$matches[4]',
        '([0-9]{4})/([0-9]{1,2})/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&feed=$matches[3]',
        '([0-9]{4})/([0-9]{1,2})/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]',
        '([0-9]{4})/([0-9]{1,2})/comment-page-([0-9]{1,})/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&cpage=$matches[3]',
        '([0-9]{4})/([0-9]{1,2})/embed/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&embed=true',
        '([0-9]{4})/([0-9]{1,2})/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&feed=$matches[3]',
        '([0-9]{4})/([0-9]{1,2})/page/?([0-9]{1,})/?$' => 'index.php?year=$matches[1]&monthnum=$matches[2]&paged=$matches[3]',
        '([0-9]{4})/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?year=$matches[1]&feed=$matches[2]',
        '([0-9]{4})/?$' => 'index.php?year=$matches[1]',
        '([0-9]{4})/comment-page-([0-9]{1,})/?$' => 'index.php?year=$matches[1]&cpage=$matches[2]',
        '([0-9]{4})/embed/?$' => 'index.php?year=$matches[1]&embed=true',
        '([0-9]{4})/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?year=$matches[1]&feed=$matches[2]',
        '([0-9]{4})/page/?([0-9]{1,})/?$' => 'index.php?year=$matches[1]&paged=$matches[2]',
        '(feed|rdf|rss|rss2|atom)/?$' => 'index.php?&feed=$matches[1]',
        '.*wp-(atom|rdf|rss|rss2|feed|commentsrss2)\\.php$' => 'index.php?feed=old',
        '.*wp-app\\.php(/.*)?$' => 'index.php?error=403',
        '.*wp-register.php$' => 'index.php?register=true',
        '.?.+?/attachment/([^/]+)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?attachment=$matches[1]&feed=$matches[2]',
        '.?.+?/attachment/([^/]+)/?$' => 'index.php?attachment=$matches[1]',
        '.?.+?/attachment/([^/]+)/comment-page-([0-9]{1,})/?$' => 'index.php?attachment=$matches[1]&cpage=$matches[2]',
        '.?.+?/attachment/([^/]+)/embed/?$' => 'index.php?attachment=$matches[1]&embed=true',
        '.?.+?/attachment/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?attachment=$matches[1]&feed=$matches[2]',
        '.?.+?/attachment/([^/]+)/trackback/?$' => 'index.php?attachment=$matches[1]&tb=1',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?attachment=$matches[1]&feed=$matches[2]',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/?$' => 'index.php?attachment=$matches[1]',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/comment-page-([0-9]{1,})/?$' => 'index.php?attachment=$matches[1]&cpage=$matches[2]',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/embed/?$' => 'index.php?attachment=$matches[1]&embed=true',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?attachment=$matches[1]&feed=$matches[2]',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/trackback/?$' => 'index.php?attachment=$matches[1]&tb=1',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?attachment=$matches[1]&feed=$matches[2]',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/?$' => 'index.php?attachment=$matches[1]',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/comment-page-([0-9]{1,})/?$' => 'index.php?attachment=$matches[1]&cpage=$matches[2]',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/embed/?$' => 'index.php?attachment=$matches[1]&embed=true',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?attachment=$matches[1]&feed=$matches[2]',
        '[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/trackback/?$' => 'index.php?attachment=$matches[1]&tb=1',
        '^index.php/wp-json/(.*)?' => 'index.php?rest_route=/$matches[1]',
        '^index.php/wp-json/?$' => 'index.php?rest_route=/',
        '^wp-json/(.*)?' => 'index.php?rest_route=/$matches[1]',
        '^wp-json/?$' => 'index.php?rest_route=/',
        '^wp-sitemap-([a-z]+?)-([a-z\\d_-]+?)-(\\d+?)\\.xml$' => 'index.php?sitemap=$matches[1]&sitemap-subtype=$matches[2]&paged=$matches[3]',
        '^wp-sitemap-([a-z]+?)-(\\d+?)\\.xml$' => 'index.php?sitemap=$matches[1]&paged=$matches[2]',
        '^wp-sitemap-index\\.xsl$' => 'index.php?sitemap-stylesheet=index',
        '^wp-sitemap\\.xml$' => 'index.php?sitemap=index',
        '^wp-sitemap\\.xsl$' => 'index.php?sitemap-stylesheet=sitemap',
        'author/([^/]+)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?author_name=$matches[1]&feed=$matches[2]',
        'author/([^/]+)/?$' => 'index.php?author_name=$matches[1]',
        'author/([^/]+)/embed/?$' => 'index.php?author_name=$matches[1]&embed=true',
        'author/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?author_name=$matches[1]&feed=$matches[2]',
        'author/([^/]+)/page/?([0-9]{1,})/?$' => 'index.php?author_name=$matches[1]&paged=$matches[2]',
        'category/(.+?)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?category_name=$matches[1]&feed=$matches[2]',
        'category/(.+?)/?$' => 'index.php?category_name=$matches[1]',
        'category/(.+?)/embed/?$' => 'index.php?category_name=$matches[1]&embed=true',
        'category/(.+?)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?category_name=$matches[1]&feed=$matches[2]',
        'category/(.+?)/page/?([0-9]{1,})/?$' => 'index.php?category_name=$matches[1]&paged=$matches[2]',
        'comments/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?&feed=$matches[1]&withcomments=1',
        'comments/embed/?$' => 'index.php?&embed=true',
        'comments/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?&feed=$matches[1]&withcomments=1',
        'embed/?$' => 'index.php?&embed=true',
        'favicon\\.ico$' => 'index.php?favicon=1',
        'feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?&feed=$matches[1]',
        'page/?([0-9]{1,})/?$' => 'index.php?&paged=$matches[1]',
        'robots\\.txt$' => 'index.php?robots=1',
        'search/(.+)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?s=$matches[1]&feed=$matches[2]',
        'search/(.+)/?$' => 'index.php?s=$matches[1]',
        'search/(.+)/embed/?$' => 'index.php?s=$matches[1]&embed=true',
        'search/(.+)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?s=$matches[1]&feed=$matches[2]',
        'search/(.+)/page/?([0-9]{1,})/?$' => 'index.php?s=$matches[1]&paged=$matches[2]',
        'tag/([^/]+)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?tag=$matches[1]&feed=$matches[2]',
        'tag/([^/]+)/?$' => 'index.php?tag=$matches[1]',
        'tag/([^/]+)/embed/?$' => 'index.php?tag=$matches[1]&embed=true',
        'tag/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?tag=$matches[1]&feed=$matches[2]',
        'tag/([^/]+)/page/?([0-9]{1,})/?$' => 'index.php?tag=$matches[1]&paged=$matches[2]',
        'type/([^/]+)/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?post_format=$matches[1]&feed=$matches[2]',
        'type/([^/]+)/?$' => 'index.php?post_format=$matches[1]',
        'type/([^/]+)/embed/?$' => 'index.php?post_format=$matches[1]&embed=true',
        'type/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$' => 'index.php?post_format=$matches[1]&feed=$matches[2]',
        'type/([^/]+)/page/?([0-9]{1,})/?$' => 'index.php?post_format=$matches[1]&paged=$matches[2]',
      ],
    ],
    'rss_use_excerpt' => '1',
    'show_avatars' => '1',
    'show_comments_cookies_opt_in' => '1',
    'show_on_front' => 'posts',
    'sidebars_widgets' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        'array_version' => 3,
        'footer' => [
          'type' => 'array',
          'value' => [
          ],
        ],
        'sidebar' => [
          'type' => 'array',
          'value' => [
            0 => 'text-5',
            1 => 'search-2',
            2 => 'text-3',
            3 => 'text-4',
            4 => 'categories-2',
          ],
        ],
        'wp_inactive_widgets' => [
          'type' => 'array',
          'value' => [
          ],
        ],
      ],
    ],
    'site_icon' => '2996',
    'siteurl' => 'https://UNDEFINED-IN-CONFIGMAPS.dev.pdkranj.si',
    'start_of_week' => '1',
    'sticky_posts' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
      ],
    ],
    'stylesheet' => 'pdkranj',
    'tag_base' => '',
    'template' => 'pdkranj',
    'theme_mods_dist' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        0 => false,
        'custom_css_post_id' => -1,
        'nav_menu_locations' => [
          'type' => 'array',
          'value' => [
            'footer' => 0,
            'header' => 3,
            'primary' => 3,
          ],
        ],
      ],
    ],
    'theme_mods_twentytwelve' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        'header_image' => 'https://UNDEFINED-IN-CONFIGMAPS.dev.pdkranj.si/wp-content/uploads/2013/07/pdkranj.jpg',
        'header_image_data' => [
          'type' => 'array',
          'value' => [
            'attachment_id' => 4,
            'height' => 250,
            'thumbnail_url' => 'https://UNDEFINED-IN-CONFIGMAPS.dev.pdkranj.si/wp-content/uploads/2013/07/pdkranj.jpg',
            'url' => 'https://UNDEFINED-IN-CONFIGMAPS.dev.pdkranj.si/wp-content/uploads/2013/07/pdkranj.jpg',
            'width' => 960,
          ],
        ],
        'header_textcolor' => '000000',
        'nav_menu_locations' => [
          'type' => 'array',
          'value' => [
            'primary' => 3,
          ],
        ],
        'sidebars_widgets' => [
          'type' => 'array',
          'value' => [
            'data' => [
              'type' => 'array',
              'value' => [
                'sidebar-1' => [
                  'type' => 'array',
                  'value' => [
                    0 => 'search-2',
                    1 => 'text-2',
                    2 => 'simple_page_to_sidebar-2',
                    3 => 'facebook-like-box-2',
                  ],
                ],
                'sidebar-2' => [
                  'type' => 'array',
                  'value' => [
                  ],
                ],
                'sidebar-3' => [
                  'type' => 'array',
                  'value' => [
                  ],
                ],
                'wp_inactive_widgets' => [
                  'type' => 'array',
                  'value' => [
                  ],
                ],
              ],
            ],
            'time' => 1621905132,
          ],
        ],
      ],
    ],
    'theme_switched' => '',
    'thread_comments' => '',
    'thread_comments_depth' => '5',
    'thumbnail_crop' => '1',
    'thumbnail_size_h' => '150',
    'thumbnail_size_w' => '150',
    'time_format' => 'G:i',
    'timezone_string' => 'Europe/Ljubljana',
    'uninstall_plugins' => [
      'action' => 'ignore',
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => NULL,
    ],
    'upload_path' => '',
    'upload_url_path' => '',
    'uploads_use_yearmonth_folders' => '1',
    'use_balanceTags' => '1',
    'use_smilies' => '1',
    'use_trackback' => '0',
    'users_can_register' => '0',
    'widget_archives' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_black-studio-tinymce' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
        2 => [
          'type' => 'array',
          'value' => [
            'text' => '',
            'title' => '',
            'type' => 'visual',
          ],
        ],
      ],
    ],
    'widget_block' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_calendar' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_categories' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
        2 => [
          'type' => 'array',
          'value' => [
            'count' => 0,
            'dropdown' => 0,
            'hierarchical' => 0,
            'title' => 'Kategorije',
          ],
        ],
      ],
    ],
    'widget_custom_html' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_facebook-activity-feed' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_facebook-follow' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_facebook-like' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_facebook-like-box' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_facebook-recommendations' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_facebook-send' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_fpw_widget' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_mec_mec_widget' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_mec_single_widget' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_media_audio' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_media_gallery' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_media_image' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_media_video' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_meta' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_nav_menu' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_pages' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_recent-comments' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_recent-posts' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_rss' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
        1 => [
          'type' => 'array',
          'value' => [
          ],
        ],
      ],
    ],
    'widget_search' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
        2 => [
          'type' => 'array',
          'value' => [
            'title' => '',
          ],
        ],
      ],
    ],
    'widget_simple_page_to_sidebar' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_tag_cloud' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
      ],
    ],
    'widget_text' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        '_multiwidget' => 1,
        3 => [
          'type' => 'array',
          'value' => [
            'filter' => false,
            'text' => '<a class="btn btn-primary btn-lg d-block" href="/podprite-nas/">Podpri društvo</a>
',
            'title' => '',
          ],
        ],
        4 => [
          'type' => 'array',
          'value' => [
            'filter' => false,
            'text' => '<a class="btn btn-secondary btn-lg d-block" href="/clanarina/">Postanite naš član</a>
',
            'title' => '',
          ],
        ],
        5 => [
          'type' => 'array',
          'value' => [
            'filter' => false,
            'text' => '<img src="https://UNDEFINED-IN-CONFIGMAPS.dev.pdkranj.si/wp-content/uploads/2021/05/pd-kranj-logo.png" style="display:block;margin: 0 auto;max-width:100%" alt="PD Kranj" />',
            'title' => '',
          ],
        ],
      ],
    ],
    'wp_force_deactivated_plugins' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
      ],
    ],
    'wp_page_for_privacy_policy' => '0',
    'wp_user_roles' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'value' => [
        'administrator' => [
          'type' => 'array',
          'value' => [
            'capabilities' => [
              'type' => 'array',
              'value' => [
                'activate_plugins' => true,
                'create_users' => true,
                'delete_others_pages' => true,
                'delete_others_posts' => true,
                'delete_pages' => true,
                'delete_plugins' => true,
                'delete_posts' => true,
                'delete_private_pages' => true,
                'delete_private_posts' => true,
                'delete_published_pages' => true,
                'delete_published_posts' => true,
                'delete_themes' => true,
                'delete_users' => true,
                'edit_dashboard' => true,
                'edit_files' => true,
                'edit_others_pages' => true,
                'edit_others_posts' => true,
                'edit_pages' => true,
                'edit_plugins' => true,
                'edit_posts' => true,
                'edit_private_pages' => true,
                'edit_private_posts' => true,
                'edit_published_pages' => true,
                'edit_published_posts' => true,
                'edit_theme_options' => true,
                'edit_themes' => true,
                'edit_users' => true,
                'export' => true,
                'import' => true,
                'install_plugins' => true,
                'install_themes' => true,
                'level_0' => true,
                'level_1' => true,
                'level_10' => true,
                'level_2' => true,
                'level_3' => true,
                'level_4' => true,
                'level_5' => true,
                'level_6' => true,
                'level_7' => true,
                'level_8' => true,
                'level_9' => true,
                'list_users' => true,
                'manage_categories' => true,
                'manage_links' => true,
                'manage_options' => true,
                'mec_add_booking' => true,
                'mec_bookings' => true,
                'mec_coupons' => true,
                'mec_import_export' => true,
                'mec_report' => true,
                'mec_settings' => true,
                'mec_shortcodes' => true,
                'moderate_comments' => true,
                'promote_users' => true,
                'publish_pages' => true,
                'publish_posts' => true,
                'publishpress_future_expire_post' => true,
                'read' => true,
                'read_private_pages' => true,
                'read_private_posts' => true,
                'remove_users' => true,
                'switch_themes' => true,
                'unfiltered_html' => true,
                'unfiltered_upload' => true,
                'update_core' => true,
                'update_plugins' => true,
                'update_themes' => true,
                'upload_files' => true,
              ],
            ],
            'name' => 'Administrator',
          ],
        ],
        'author' => [
          'type' => 'array',
          'value' => [
            'capabilities' => [
              'type' => 'array',
              'value' => [
                'delete_posts' => true,
                'delete_published_posts' => true,
                'edit_posts' => true,
                'edit_published_posts' => true,
                'level_0' => true,
                'level_1' => true,
                'level_2' => true,
                'publish_posts' => true,
                'read' => true,
                'upload_files' => true,
              ],
            ],
            'name' => 'Author',
          ],
        ],
        'contributor' => [
          'type' => 'array',
          'value' => [
            'capabilities' => [
              'type' => 'array',
              'value' => [
                'delete_posts' => true,
                'edit_posts' => true,
                'level_0' => true,
                'level_1' => true,
                'read' => true,
              ],
            ],
            'name' => 'Contributor',
          ],
        ],
        'editor' => [
          'type' => 'array',
          'value' => [
            'capabilities' => [
              'type' => 'array',
              'value' => [
                'delete_others_pages' => true,
                'delete_others_posts' => true,
                'delete_pages' => true,
                'delete_posts' => true,
                'delete_private_pages' => true,
                'delete_private_posts' => true,
                'delete_published_pages' => true,
                'delete_published_posts' => true,
                'edit_others_pages' => true,
                'edit_others_posts' => true,
                'edit_pages' => true,
                'edit_posts' => true,
                'edit_private_pages' => true,
                'edit_private_posts' => true,
                'edit_published_pages' => true,
                'edit_published_posts' => true,
                'level_0' => true,
                'level_1' => true,
                'level_2' => true,
                'level_3' => true,
                'level_4' => true,
                'level_5' => true,
                'level_6' => true,
                'level_7' => true,
                'manage_categories' => true,
                'manage_links' => true,
                'moderate_comments' => true,
                'publish_pages' => true,
                'publish_posts' => true,
                'read' => true,
                'read_private_pages' => true,
                'read_private_posts' => true,
                'unfiltered_html' => true,
                'upload_files' => true,
              ],
            ],
            'name' => 'Editor',
          ],
        ],
        'subscriber' => [
          'type' => 'array',
          'value' => [
            'capabilities' => [
              'type' => 'array',
              'value' => [
                'level_0' => true,
                'read' => true,
              ],
            ],
            'name' => 'Subscriber',
          ],
        ],
      ],
    ],
  ],
];
