<?php

// Generated by `wp configmaps generate --from-db --values-from-db` on 2022-01-11T17:55:43+00:00.

return [
  'metadata' => [
    'version' => 1,
  ],
  'data' => [
    'home' => 'https://XXX.dev.pdkranj.si',
    'siteurl' => 'https://XXX.dev.pdkranj.si',
  ],
];
