<?php

// Generated by `wp configmaps update` on 2022-01-14T01:56:46+00:00.

return [
  'metadata' => [
    'version' => 1,
  ],
  'data' => [
    'blogname' => 'DEV PD Kranj DEV',
    'dashboard_widget_options' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'undef-key-action-dump' => 'ignore',
      'value' => [
        'dashboard_incoming_links' => [
          'type' => 'array',
          'undef-key-action-dump' => 'ignore',
          'value' => [
            'home' => 'http://docker.dev.pdkranj.si',
            'link' => 'http://blogsearch.google.com/blogsearch?scoring=d&partner=wordpress&q=link:http://docker.dev.pdkranj.si/',
            'url' => 'http://blogsearch.google.com/blogsearch_feeds?scoring=d&ie=utf-8&num=10&output=rss&partner=wordpress&q=link:http://docker.dev.pdkranj.si/',
          ],
        ],
      ],
    ],
    'home' => 'http://docker.dev.pdkranj.si',
    'siteurl' => 'http://docker.dev.pdkranj.si',
    'theme_mods_twentytwelve' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'undef-key-action-dump' => 'ignore',
      'value' => [
        'header_image' => 'http://docker.dev.pdkranj.si/wp-content/uploads/2013/07/pdkranj.jpg',
        'header_image_data' => [
          'type' => 'array',
          'undef-key-action-dump' => 'ignore',
          'value' => [
            'thumbnail_url' => 'http://docker.dev.pdkranj.si/wp-content/uploads/2013/07/pdkranj.jpg',
            'url' => 'http://docker.dev.pdkranj.si/wp-content/uploads/2013/07/pdkranj.jpg',
          ],
        ],
      ],
    ],
    'widget_text' => [
      'encoding' => 'serialize',
      'type' => 'array',
      'undef-key-action-dump' => 'ignore',
      'value' => [
        5 => [
          'type' => 'array',
          'undef-key-action-dump' => 'ignore',
          'value' => [
            'text' => '<img src="http://docker.dev.pdkranj.si/wp-content/uploads/2021/05/pd-kranj-logo.png" style="display:block;margin: 0 auto;max-width:100%" alt="PD Kranj" />',
          ],
        ],
      ],
    ],
  ],
];
