name: "Deploy PROD"



on:
    workflow_dispatch:

    push:
        tags:
            - 'prod-*'



jobs:

    deploy:
        name: 'Deploy to www.pdkranj.si'

        # Only run this job in the main repository, and not in any of the forks.
        if: "github.repository == 'aokranj/website-pdkranj.si'"

        runs-on: ubuntu-latest
        steps:

            -   name: "Clone the repository"
                uses: actions/checkout@v2
                with:
                    fetch-depth: 1
                    ref: ${{github.ref_name}}

            # Dirty workaround for https://github.com/actions/checkout/issues/290
            -   name: "Work around the annotated tag checkout issue that is endemic to actions/checkout@v2"
                run: |
                    git fetch --force --tags
                    git checkout ${{github.ref_name}}

            -   name: "Verify the deployment tag"
                run: ./sbin/deploy-prod-verify-tag ${{github.ref_name}}

            -   name: "SSH to www.pdkranj.si and deploy the latest code there"
                uses: appleboy/ssh-action@master
                with:
                    host: www.pdkranj.si
                    username: pd-prod
                    key: ${{ secrets.SSH_PRIVKEY_GITHUB_TO_PD_PROD }}
                    script_stop: true
                    script: |
                        cd www/www.pdkranj.si
                        git fetch
                        git checkout "${{github.ref_name}}"
                        ./sbin/deploy-here



            -   name: Slack Notification - Success
                uses: rtCamp/action-slack-notify@v2
                env:
                    SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK_RELEASES }}'
                    SLACK_ICON: 'https://www.pdkranj.si/wp-content/uploads/2021/05/cropped-pd-kranj-logo-300-192x192.png'
                    SLACK_USERNAME: '[PROD] Deploy to www.pdkranj.si'
                    SLACK_COLOR: 'good'
                    SLACK_TITLE: ''
                    SLACK_MESSAGE: 'Deployment to <https://www.pdkranj.si> has been successful.'
                    SLACK_LINK_NAMES: 'true'
                    SLACK_FOOTER: ''
                    MSG_MINIMAL: 'ref,commit'

            -   name: Slack Notification - Failure
                uses: rtCamp/action-slack-notify@v2
                if: ${{ failure() }}
                env:
                    SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK_RELEASES }}'
                    SLACK_ICON: 'https://www.pdkranj.si/wp-content/uploads/2021/05/cropped-pd-kranj-logo-300-192x192.png'
                    SLACK_USERNAME: '[PROD] Deploy to www.pdkranj.si'
                    SLACK_COLOR: '#a82525'
                    SLACK_TITLE: ''
                    SLACK_MESSAGE: 'Deployment to <https://www.pdkranj.si> has FAILED - notifying this @channel now.'
                    SLACK_LINK_NAMES: 'true'
                    SLACK_FOOTER: ''
                    MSG_MINIMAL: 'ref,commit,actions url'
