name: "Deploy STG"



on:
    workflow_dispatch:

    push:
        branches:
            - master



jobs:

    deploy:
        name: "Deploy to stg.pdkranj.si"

        # Only run this job in the main repository, and not in any of the forks.
        if: "github.repository == 'aokranj/website-pdkranj.si'"

        runs-on: ubuntu-latest
        steps:
            -   name: "SSH to stg.pdkranj.si and deploy the latest code there"
                uses: appleboy/ssh-action@master
                with:
                    host: stg.pdkranj.si
                    username: pd-stg
                    key: ${{ secrets.SSH_PRIVKEY_GITHUB_TO_PD_STG }}
                    script_stop: true
                    script: |
                        cd www/stg.pdkranj.si
                        git pull
                        ./sbin/deploy-here
